config/routes.rb
Rails.application.routes.draw do

  devise_for :users
root "books#index"

    resources :books do
        resources :shops
    end

end

app/models/book.rb
class Book < ActiveRecord::Base
    has_many :shops
end

app/models/shop.rb
class Shop < ActiveRecord::Base
    belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all

        @bookAdd = Book.new

        render "index"
    end

    def create
        book = Book.create(book_params)

        redirect_to "/books"

    end

    def edit

        @book = Book.find(params[:id])

        render "edit"
    end

    def update

        book = Book.find(params[:id])

        book.update_attributes(book_params)

        redirect_to "/books"

    end

    def destroy

        book = Book.find(params[:id])

        book.destroy

        redirect_to books_path
    end

private

    def book_params
        params.require(:book).permit(:title,:author,:releaseDate,:imgScr)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    def index

        @shops = Book.find(params[:book_id]).shops.all

    end

    def new
        @book = Book.find(params[:book_id])
        @shop = Shop.new
    end

    def create
        Book.find(params[:book_id]).shops.create(shop_params)

        redirect_to book_shops_path
    end

    def destroy

    end

    def shop_params
        params.require(:shop).permit(:ShopName,:Address,:website,:book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blm_helper.rb
module BlmHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/books/edit.html.erb
<div class="container well margin-top-20 small-container">
	<div>
		<a href="/books"><< Go Back</a>
	</div>
<%= form_for(@book, method: "PUT") do |f| %>
	<div class="bold margin-top-20">
		Title
	</div>
	<div class="margin-top-20">

		<%= f.text_field :title %>
	</div>
	<div class="bold margin-top-20">
		Author
	</div>
	<div class="margin-top-20">

		<%= f.text_field :author %>
	</div>
	<div class="bold margin-top-20">
		Release Date
	</div>
	<div class="margin-top-20">

		<%= f.text_field :releaseDate %>
	</div>
	<div class="bold margin-top-20">
		Image
	</div>
	<div class="margin-top-20">

		<%= f.text_field :imgScr %>
	</div>
	<div class="margin-top-20">
		<a href="/books" class="btn btn-default">Cancel</a>
		<button type="submit" class="btn btn-success">Submit Edits</button>
	</div>
<% end %>
</div>

app/views/books/index.html.erb
<% if user_signed_in? %>
    <div class="container">
      <%= link_to 'Sign Out', destroy_user_session_path, method: 'DELETE', class: 'btn btn-default' %>
    </div>

  <div class="container">
    <div class="margin-top-20">
      <a href="#" data-toggle="modal" data-target="#add-book-modal" class="btn btn-primary">Add New Book</a>
    </div>
    <!--One Wine-->
    <% @books.each do |book|%>
    <div class="row margin-top-20 wine-container">
      <div class="col-sm-3">
        <img src="<%=book.imgScr%>" class="img-responsive" />
      </div>
      <div class="col-sm-9">
        <div class="margin-top-20">
          <span class="bold">Title: </span><span><%=book.title%></span>
        </div>
        <div>
          <span class="bold">Author: </span><span><%=book.author%></span>
        </div>
        <div>
          <span class="bold">Release Date: </span><span><%=book.releaseDate%></span>
        </div>
        <div class="margin-top-20">
          <a href="/books/<%=book.id%>/edit" class="btn btn-default">Edit Book</a>
          <a href="<%= book_shops_path(book.id) %>" class="btn btn-default" >Book Carriers</a>
          <%= link_to 'Destroy', book , method: 'DELETE', class: 'btn btn-default', data: {confirm: 'are you sure?'} %>

        </div>
      </div>
    </div>
    <%end%>
    <!--/One Book-->
  </div>

  <!--Add Wine Modal-->
  <%= form_for @bookAdd do |f| %>
  <div id="add-book-modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Add New Wine</h4>
        </div>
        <div class="modal-body">
          <div class="bold">
            Title
          </div>
          <div class="margin-top-20">
            <%= f.text_field :title %>
          </div>
          <div class="bold margin-top-20">
            Author
          </div>
          <div class="margin-top-20">
            <%= f.text_field :author %>
          </div>
          <div class="bold margin-top-20">
            Release Date
          </div>
          <div class="margin-top-20">
            <%= f.text_field :releaseDate %>
          </div>
          <div class="bold margin-top-20">
            Image
          </div>
          <div class="margin-top-20">
            <%= f.text_field :imgScr %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save Book</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <!--/Add Wine Modal-->
  <% end %>

<%end%>

<% if !user_signed_in? %>

   <a href="<%=new_user_session_path%>" class="btn btn-primary">Sign in</a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookLibManager</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>

<%= yield %>


</body>
</html>

app/views/shops/index.html.erb
<a href="<%=new_book_shop_path%>" class="btn btn-default">New Carrier</a>
<div class="container well margin-top-20 small-container">
    <table class="table">
        <% @shops.each do |s| %>
            <tr>
                <td><%=s.ShopName %></td>
                <td><%=s.Address %></td>
                <td><%=s.website %></td>
            </tr>
        <%end%>
    </table>

</div>

app/views/shops/new.html.erb
<div class="container well margin-top-20 small-container">
    <%= form_for [@book,@shop] do |shop| %>
    <div class="bold margin-top-20">
    		Shop Name
    	</div>
    	<div class="margin-top-20">

    		<%= shop.text_field :ShopName %>
    	</div>
    	<div class="bold margin-top-20">
    		Address
    	</div>
    	<div class="margin-top-20">
    		<%= shop.text_field :Address %>
    	</div>
    	<div class="bold margin-top-20">
    		Website
    	</div>
    	<div class="margin-top-20">

    		<%= shop.text_field :website%>
    	</div>
    	<div class="margin-top-20">
    		<a href="<%=book_shops_path%>" class="btn btn-default">Cancel</a>
    		<button type="submit" class="btn btn-success">Submit</button>
    	</div>

    <%end%>
</div>